### ISSUE TITLE
how to give audio input and enable audio patterns?

### ISSUE THREAD

**Issue by uttaran18** [marcmerlin/Table_Mark_Estes#1]
how to give audio input and enable audio patterns ?  what is the specific matrix size for enabling audio patterns ? Thank you.

**Comment by marcmerlin** [comment]
Howdy. I didn't write this code and I'm not using audio input. You should look at the original code before I removed the audio support.
https://github.com/marcmerlin/Table_Mark_Estes/commit/cda248f1e7087ec0914cb548aed11fc5f0982d6e#diff-b6cd45c11d9cfbe9b6e9b357f96d95be
with git, just go back to revision #1.
I think it uses a 2nd MCU though, I don't have that code, and I can't tell you more about it.
You could try to contact Mark Estes on FastLED G+ to ask him
